---
 - hosts: all
   become: no
   gather_facts: yes

 - hosts: localhost
   connection: local
   gather_facts: yes
   become: no
   vars:
     # Comment if you want to use ansible_ssh_user or ansible_user_id
     ssh_user: username
     # Keep comented if you want to use your default key
     # ssh_key_file: ~/.ssh/private_key
   roles:
    - cuttlerat.ansible-ssh_config
